name: test
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
    tags-ignore:
      - "*"

jobs:
  test:
    container: ubuntu:focal
    runs-on: ubuntu-latest
    # if: "!contains(github.event.commits[0].message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
      - name: Prepare test environment
        shell: bash
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt update -qq
          apt install --no-install-recommends -y iproute2 bc
          cp tests/xrescat_mock /usr/bin/xrescat
          cp tests/i3-msg_mock /usr/bin/i3-msg
      - name: Run net-traffic test
        shell: bash
        run: |
          tests/net-traffic_test.sh
  build_bionic:
    container:
      image: docker.pkg.github.com/regolith-linux/regolith-deb-builder/regolith-deb-builder:bionic
      credentials:
        username: ${{ github.actor }}
        password: ${{secrets.GITHUB_TOKEN}}
    name: Build package on Bionic
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - name: Build package
        shell: bash
        run: |
          gbp buildpackage --no-sign
          [ $(ls ../*.deb | wc -l) == "21" ]
  build_focal:
    container:
      image: docker.pkg.github.com/regolith-linux/regolith-deb-builder/regolith-deb-builder:focal
      credentials:
        username: ${{ github.actor }}
        password: ${{secrets.GITHUB_TOKEN}}
    name: Build package on Focal
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - name: Build package
        shell: bash
        run: |
          gbp buildpackage --no-sign
          [ $(ls ../*.deb | wc -l) == "21" ]
  build_groovy:
    container:
      image: docker.pkg.github.com/regolith-linux/regolith-deb-builder/regolith-deb-builder:groovy
      credentials:
        username: ${{ github.actor }}
        password: ${{secrets.GITHUB_TOKEN}}
    name: Build package on Groovy
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - name: Build package
        shell: bash
        run: |
          gbp buildpackage --no-sign
          [ $(ls ../*.deb | wc -l) == "21" ]
